### ISSUE TITLE
Persistent bits in board status library

### ISSUE THREAD

**Issue by LukeWalker-CA** [copenhagenatomics/CA_Embedded_Libraries#10]
In functions such as the following, the behaviour results in 1's being persistent:
```
void bsSetError(uint32_t field) { BS.boardStatus |= (BS_ERROR_Msk | field); }
void bsSetField(uint32_t field){ BS.boardStatus |= field; }
```
Probably the expected behaviour is that setting a field value (e.g. 01) would clear the previous value:
```
print(error); /* 0b00000011 */
bsSetError(0b10000010); 
print(error); /* 0b10000011 */ /* Expect error = 0b10000010 */

**Comment by matias-cphatomics** [comment]
Disagree. 

I think the expected behaviour of bsSetField is simply that you are setting the field given as an input parameter. This is also how it works in all status registries in the STM32 library. 

Implementing the behaviour described above would mean that you would need to keep a copy of all states because you would need to set all fields for every update.

**Comment by LukeWalker-CA** [comment]
I can't see that that is how it works in the STM32 library, except that maybe they only do it for single bits rather than ranges of bits. Then it makes sense. Or maybe I just missed it.

Maybe the intended usage just needs to be made clearer. Example with changing states:
```
state0 = 0b00; state1 = 0b01; state2 = 0b10; state3 = 0b11;

bsClearField(STATE_Msk);
bsSetField(state0);
print(status); /* state0 */
bsClearField(STATE_Msk);
bsSetField(state1);
print(status); /* state1 */
bsSetField(state2);
print(status); /* state3 */ /* Incorrect usage */
bsClearField(STATE_Msk);
bsSetField(state2);
print(status); /* state2 */ /* Better */

**Comment by matias-cphatomics** [comment]
Yes for ranges of bit fields I see the issue. It is now being handled in #11 .
